name: chengdu iptv build

on:
  workflow_dispatch:
  #schedule:
    #- cron: "30 3 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install m3u8
          pip install bs4
          pip install lxml
          pip install html5lib
          pip install strict-rfc3339

      - name: Build home
        run: |
          python3 ./script/home.py

      - name: Check file sizes
        run: |
          ls -lh home/iptv.m3u8

      - name: 整理文件
        run: |
          mkdir -p dcx
          mv home/iptv.m3u8 dcx/
          
      - name: 上传软件
        uses: actions/upload-artifact@main
        with:
          name: "iptv.m3u8"
          path: ${{ github.workspace }}/dcx
